server: 
  host: "localhost"
  port: "6969"

resources:
  - name: Google
    endpoint: /goo
    destination_url: "https://google.com"
    rate_limits:
      GET:
        strategy: SLIDING-WINDOW-LOG
        capacity: 10
        rate: 10/s
    
  - name: Facebook
    endpoint: /face
    destination_url: "https://facebook.com"
    rate_limits:
      GET:
        strategy: SLIDING-WINDOW-LOG
        rate: 10K/s